version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - ls -la build
      - cp Dockerfile build/Dockerfile
artifacts:
  files:
    - '**/*'
  base-directory: build